---
title: "NYC Taxi Ride Data: 2010 - 2012"
author: "David Jackson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(duckdb)
library(scales)
library(DBI)
```

## Open DB and List Tables
```{r}
con <- dbConnect(duckdb::duckdb(), dbdir = "./nyctaxis.duckdb", read_only = FALSE)
```
```{r}
data <- dbGetQuery(con,"SELECT * FROM jan;") 
data$year <- lubridate::year(data$start_date)
  data %>%ggplot() + geom_col(aes(x=start_date,y=n,col=year))
```
```{r}
data %>%filter(year =='2010') %>% ggplot(aes(x=start_date,y=n)) + geom_col() +
  labs(title ="Jan 2010") + scale_y_continuous(labels=comma)
data %>%filter(year =='2011') %>% ggplot(aes(x=start_date,y=n)) + geom_col() +
  labs(title ="Year 2011") + scale_y_continuous(labels=comma)
data %>%filter(year =='2012') %>% ggplot(aes(x=start_date,y=n)) + geom_col() +
  labs(title ="Year 2012") + scale_y_continuous(labels=comma)
```
```{r}
data %>% group_by(year) %>% 
  summarize(min_rides = min(n),
            avg_rides = mean(n),
            max_rides = max(n),
            sum_rides = sum(n)
            )
```



```{r}
db1 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db1 group by start_date")
```
```{r}
db2 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db2 group by start_date")
```
```{r}
db3 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db3 group by start_date")
```
```{r}
db4 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db4 group by start_date")
```

```{r}
db5 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db5 group by start_date")
```
```{r}
db6 <- dbGetQuery(con,"SELECT start_date,count(*) as ride_count 
           FROM db6 group by start_date")
```

```{r}
ride_counts <- bind_rows(db1,db2,db3,db4,db5,db6)
```

```{r}
ride_counts %>% ggplot(aes(x=start_date,y=ride_count)) + geom_line() +
  labs(title ="NYC Taxi Ride Counts by Date",x="Ride Date",y="Ride Counts") +
  scale_y_continuous(labels = comma ) + geom_smooth(span=0.75)
```

```{r}
ride_counts$mov_avg <- forecast::ma(ride_counts$ride_count,28)
ride_counts$yr <- lubridate::year(ride_counts$start_date)
```
```{r}
ggplot(ride_counts) + geom_line(aes(x=start_date,y=mov_avg,col="28 Day")) +
  geom_point(aes(x=start_date,y=ride_count))

```
```{r}
ride_counts %>% ggplot(aes(x=start_date,y=ride_count)) + geom_col() +
  labs(title ="NYC Taxi Ride Counts by Date",x="Ride Date",y="Ride Counts") +
  scale_y_continuous(labels = comma ) 
```

```{r}
ride_counts %>% ggplot(aes(x=ride_count)) + geom_histogram() +
  facet_wrap(~yr)
```

```{r}
ride_counts %>% ggplot(aes(x=ride_count)) + geom_boxplot() +
  facet_wrap(~yr)
```